services:
  builder:
    image: openwrt/sdk:x86_64-main
    container_name: openwrt-docker-builder
    hostname: openwrt-docker-builder
    restart: always
    init: true
    user: ${UID?}:${GID?}
    network_mode: bridge
    env_file:
      - .env
    volumes:
      # will create a bin directory with root permissions (don't do this)
      # why only `bin` directory would be created with root permissions?
      # - ../artifacts/bin/targets:/builder/bin/targets

      - ../custom/files:/builder/files
      - ./feeds.conf.default:/builder/feeds.conf.default
      - ./.generated.config:/builder/.generated.config

      # cache
      - ./.cache/feeds:/builder/feeds
      - ./.cache/dl:/builder/dl
    stdin_open: true # keep running without shutting down
