services:
  builder:
    # image: openwrt/sdk:x86_64-main
    image: ghcr.io/openwrt/sdk:x86_64-SNAPSHOT
    # image: ubuntu:22.04
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: openwrt-docker-builder
    hostname: openwrt-docker-builder
    restart: always
    init: true
    user: ${UID?}:${GID?}
    network_mode: bridge
    # env_file:
    #   - .env
    # volumes:
    #   # will create a bin directory with root permissions (don't do this)
    #   # why only `bin` directory would be created with root permissions?
    #   # - ../artifacts/bin/targets:/builder/bin/targets

    #   - ../custom/files:/builder/files
    #   - ./feeds.conf.default:/builder/feeds.conf.default
    #   - ./.generated.config:/builder/.generated.config

    #   # custom scripts
    #   - ./run-builder.sh:/builder/run-builder.sh
    #   - ./setup-prebuilt.sh:/builder/setup-prebuilt.sh

    #   # cache
    #   - ../.cache/dl:/builder/dl
    #   - ../.cache/.ccache:/builder/.ccache
    stdin_open: true # keep running without shutting down
