name: openwrt image ci

on:
  repository_dispatch:
  workflow_dispatch:

env:
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  TZ: UTC

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build OpenWrt ${{ matrix.version }} Firmware ${{ matrix.target }}
    strategy:
      fail-fast: true
      matrix:
        version:
          - "snapshot"
          # - "23.05.2"
        target:
          - "x86/64"

    steps:
      - name: Space cleanup and initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          make install prerequisites
          sudo -E timedatectl set-timezone "$TZ"

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Obtain OpenWRT sources and prebuilt toolchain
        run: |
          make setup-openwrt-src OPENWRT_VERSION=${{ matrix.version }}
          make install-prebuilt-sdk

      - name: Get current date
        id: date
        run: |
          echo "date=$(date +'%m/%d_%Y_%H/%M')" >> $GITHUB_ENV
          echo "date2=$(date +'%Y/%m %d')" >> $GITHUB_ENV
          echo "date3=$(date +'%m.%d')" >> $GITHUB_ENV
          VERSION="$(echo "${{ github.event.action }}" | grep -Eo " [0-9.]+" | sed -e 's/ //')" || true
          [ "$VERSION" ] && echo "VERSION=$VERSION" >> $GITHUB_ENV || echo "VERSION=$(date +'%m.%d')" >> $GITHUB_ENV

      - name: Provision custom configurations
        run: make provision

      - name: Update and install feeds
        run: make feeds

      - name: Generate configuration file
        run: make defconfig

      - name: Download packages
        run: make download

      - name: Cache
        uses: klever1988/cachewrtbuild@main
        with:
          ccache: "true"
          prefix: ${{ github.workspace }}/openwrt

      - name: Compile the firmware and targets
        run: |
          echo -e "Use $(nproc) threads to compile ..."
          make build || make build-debug
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin

      - name: Prepare artifacts
        run: |
          mkdir -p ./artifacts/buildinfo
          mkdir -p ./artifacts/targets
          cp -rf $(find ./openwrt/bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifacts/buildinfo/
          cp -rf $(find ./openwrt/bin/targets/ -type f ! -name "*.buildinfo" ! -name "*.manifest") ./artifacts/targets/

      # - name: Organize files
      #   id: organize
      #   if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      #   run: |
      #     mkdir firmware
      #     mv -f openwrt/bin/targets/*/*/{*combined*,*sysupgrade*} ./firmware/ 2>/dev/null || true
      #     cp openwrt/.config  ./firmware/${{matrix.target}}.config
      #     cp openwrt/build_dir/target-*/linux-*/linux-*/.config ./firmware/${{matrix.target}}_kernel.config
      #     cd firmware
      #     echo "v${{ env.date2 }}" > version.txt
      #     md5=$((md5sum *squashfs-sysupgrade* || md5sum *squashfs-combined-efi*) | awk '{print $1}') 2>/dev/null
      #     echo $md5 >> version.txt
      #     rename -v "s/^immortalwrt/${{ env.VERSION }}-openwrt/" * || true
      #     rename -v "s/friendlyarm_//" *gz
      #     echo $md5 >> version.txt
      #     echo ${{matrix.target}} >> version.txt
      #     rm -rf sha256sums
      #     echo "FIRMWARE=$PWD" >> $GITHUB_ENV

      - name: Upload buildinfo
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt_buildinfo
          path: ./artifacts/buildinfo/

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt_firmware
          path: ./artifacts/targets/
